name: Deploy Lambda with Terraform
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/gh-actions-role
          aws-region: us-west-2

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest app/test_main.py

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init \
            -backend-config="key=${{ vars.COMPONENT }}/${{ vars.ENV }}/terraform.tfstate"
      

      - name: Terraform Plan
        id: plan
        working-directory: infra
        env:
          TF_VAR_environment: ${{ vars.ENV }}
          TF_VAR_aws_account: ${{ vars.AWS_ACCOUNT }}
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra
        run: | 
          terraform apply -auto-approve tfplan